# Copyright (c) Microsoft. All rights reserved.

from ._agent import WorkflowAgent
from ._agent_executor import (
    AgentExecutor,
    AgentExecutorRequest,
    AgentExecutorResponse,
)
from ._checkpoint import (
    CheckpointStorage,
    FileCheckpointStorage,
    InMemoryCheckpointStorage,
    WorkflowCheckpoint,
)
from ._checkpoint_summary import WorkflowCheckpointSummary, get_checkpoint_summary
from ._concurrent import ConcurrentBuilder
from ._const import (
    DEFAULT_MAX_ITERATIONS,
)
from ._edge import (
    Case,
    Default,
    Edge,
    FanInEdgeGroup,
    FanOutEdgeGroup,
    SingleEdgeGroup,
    SwitchCaseEdgeGroup,
    SwitchCaseEdgeGroupCase,
    SwitchCaseEdgeGroupDefault,
)
from ._edge_runner import create_edge_runner
from ._events import (
    AgentRunEvent,
    AgentRunUpdateEvent,
    ExecutorCompletedEvent,
    ExecutorEvent,
    ExecutorFailedEvent,
    ExecutorInvokedEvent,
    RequestInfoEvent,
    SuperStepCompletedEvent,
    SuperStepStartedEvent,
    WorkflowErrorDetails,
    WorkflowEvent,
    WorkflowEventSource,
    WorkflowFailedEvent,
    WorkflowLifecycleEvent,
    WorkflowOutputEvent,
    WorkflowRunState,
    WorkflowStartedEvent,
    WorkflowStatusEvent,
)
from ._executor import (
    Executor,
    handler,
)
from ._function_executor import FunctionExecutor, executor
from ._group_chat import (
    DEFAULT_MANAGER_INSTRUCTIONS,
    DEFAULT_MANAGER_STRUCTURED_OUTPUT_PROMPT,
    GroupChatBuilder,
    GroupChatDirective,
    GroupChatStateSnapshot,
    ManagerDirectiveModel,
)
from ._handoff import HandoffBuilder, HandoffUserInputRequest
from ._magentic import (
    MagenticAgentDeltaEvent,
    MagenticAgentMessageEvent,
    MagenticBuilder,
    MagenticContext,
    MagenticFinalResultEvent,
    MagenticManagerBase,
    MagenticOrchestratorMessageEvent,
    MagenticPlanReviewDecision,
    MagenticPlanReviewReply,
    MagenticPlanReviewRequest,
    StandardMagenticManager,
)
from ._orchestration_state import OrchestrationState
from ._request_info_mixin import response_handler
from ._runner import Runner
from ._runner_context import (
    InProcRunnerContext,
    Message,
    RunnerContext,
)
from ._sequential import SequentialBuilder
from ._shared_state import SharedState
from ._type_adapters import (
    ConversationToText,
    FunctionAdapter,
    IdentityAdapter,
    ItemToList,
    ListToItem,
    MessageWrapper,
    SingleMessageExtractor,
    TextToConversation,
    TypeAdapter,
    dict_to_struct_adapter,
    find_adapter,
    json_deserializer,
    json_serializer,
    struct_to_dict_adapter,
)
from ._validation import (
    EdgeDuplicationError,
    GraphConnectivityError,
    TypeCompatibilityError,
    ValidationTypeEnum,
    WorkflowValidationError,
    validate_workflow_graph,
)
from ._viz import WorkflowViz
from ._workflow import Workflow, WorkflowRunResult
from ._workflow_builder import ConnectionHandle, MergeResult, WorkflowBuilder, WorkflowConnection
from ._workflow_context import WorkflowContext
from ._workflow_executor import SubWorkflowRequestMessage, SubWorkflowResponseMessage, WorkflowExecutor

__all__ = [
    "DEFAULT_MANAGER_INSTRUCTIONS",
    "DEFAULT_MANAGER_STRUCTURED_OUTPUT_PROMPT",
    "DEFAULT_MAX_ITERATIONS",
    "AgentExecutor",
    "AgentExecutorRequest",
    "AgentExecutorResponse",
    "AgentRunEvent",
    "AgentRunUpdateEvent",
    "Case",
    "CheckpointStorage",
    "ConcurrentBuilder",
    "ConnectionHandle",
    "ConversationToText",
    "Default",
    "Edge",
    "EdgeDuplicationError",
    "Executor",
    "ExecutorCompletedEvent",
    "ExecutorEvent",
    "ExecutorFailedEvent",
    "ExecutorInvokedEvent",
    "FanInEdgeGroup",
    "FanOutEdgeGroup",
    "FileCheckpointStorage",
    "FunctionAdapter",
    "FunctionExecutor",
    "GraphConnectivityError",
    "GroupChatBuilder",
    "GroupChatDirective",
    "GroupChatStateSnapshot",
    "HandoffBuilder",
    "HandoffUserInputRequest",
    "IdentityAdapter",
    "InMemoryCheckpointStorage",
    "InProcRunnerContext",
    "ItemToList",
    "ListToItem",
    "MagenticAgentDeltaEvent",
    "MagenticAgentMessageEvent",
    "MagenticBuilder",
    "MagenticContext",
    "MagenticFinalResultEvent",
    "MagenticManagerBase",
    "MagenticOrchestratorMessageEvent",
    "MagenticPlanReviewDecision",
    "MagenticPlanReviewReply",
    "MagenticPlanReviewRequest",
    "ManagerDirectiveModel",
    "MergeResult",
    "Message",
    "MessageWrapper",
    "OrchestrationState",
    "RequestInfoEvent",
    "Runner",
    "RunnerContext",
    "SequentialBuilder",
    "SharedState",
    "SingleEdgeGroup",
    "SingleMessageExtractor",
    "StandardMagenticManager",
    "SubWorkflowRequestMessage",
    "SubWorkflowResponseMessage",
    "SuperStepCompletedEvent",
    "SuperStepStartedEvent",
    "SwitchCaseEdgeGroup",
    "SwitchCaseEdgeGroupCase",
    "SwitchCaseEdgeGroupDefault",
    "TextToConversation",
    "TypeAdapter",
    "TypeCompatibilityError",
    "ValidationTypeEnum",
    "Workflow",
    "WorkflowAgent",
    "WorkflowBuilder",
    "WorkflowCheckpoint",
    "WorkflowCheckpointSummary",
    "WorkflowConnection",
    "WorkflowContext",
    "WorkflowErrorDetails",
    "WorkflowEvent",
    "WorkflowEventSource",
    "WorkflowExecutor",
    "WorkflowFailedEvent",
    "WorkflowLifecycleEvent",
    "WorkflowOutputEvent",
    "WorkflowRunResult",
    "WorkflowRunState",
    "WorkflowStartedEvent",
    "WorkflowStatusEvent",
    "WorkflowValidationError",
    "WorkflowViz",
    "create_edge_runner",
    "dict_to_struct_adapter",
    "executor",
    "find_adapter",
    "get_checkpoint_summary",
    "handler",
    "json_deserializer",
    "json_serializer",
    "response_handler",
    "struct_to_dict_adapter",
    "validate_workflow_graph",
]
